spring:
  # Persistence properties
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: 2005
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.hibernate: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO