--CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.category
(
    category_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(255) not null
);