CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.good
(
    good_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER REFERENCES category(category_id),
    good_name  VARCHAR(255) not null ,
    good_price INT NOT NULL
);

